/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.apotek;

/**
 *
 * @author ACER TRAVELMATE
 */
public class MenuApotekerGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MenuApotekerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        APOTEKER = new javax.swing.JButton();
        OBAT = new javax.swing.JButton();
        PASIEN = new javax.swing.JButton();
        RESEP = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        APOTEKER.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        APOTEKER.setText("APOTEKER");
        APOTEKER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APOTEKERActionPerformed(evt);
            }
        });
        getContentPane().add(APOTEKER, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 230, 60));

        OBAT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OBAT.setText("OBAT");
        OBAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBATActionPerformed(evt);
            }
        });
        getContentPane().add(OBAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 240, 60));

        PASIEN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PASIEN.setText("PASIEN");
        PASIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASIENActionPerformed(evt);
            }
        });
        getContentPane().add(PASIEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 240, 60));

        RESEP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RESEP.setText("RESEP");
        RESEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESEPActionPerformed(evt);
            }
        });
        getContentPane().add(RESEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 230, 60));

        Kembali.setText("Keluar");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Menu Apoteker");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 270, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MenuApoteker.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OBATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBATActionPerformed
        this.dispose(); // Menutup jendela login
        ObatGUI obat = new ObatGUI();
        obat.setVisible(true);
    }//GEN-LAST:event_OBATActionPerformed

    private void APOTEKERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APOTEKERActionPerformed
        this.dispose(); // Menutup jendela login
        ApotekerGUI apoteker = new ApotekerGUI();
        apoteker.setVisible(true);
    }//GEN-LAST:event_APOTEKERActionPerformed

    private void PASIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASIENActionPerformed
        this.dispose(); // Menutup jendela login
        PasienGUI pasien = new PasienGUI();
        pasien.setVisible(true);
    }//GEN-LAST:event_PASIENActionPerformed

    private void RESEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESEPActionPerformed
        this.dispose(); // Menutup jendela login
        ResepGUI resep = new ResepGUI();
        resep.setVisible(true);
    }//GEN-LAST:event_RESEPActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Menutup jendela login
        StartGUI start = new StartGUI();
        start.setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuApotekerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuApotekerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuApotekerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuApotekerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuApotekerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton APOTEKER;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton OBAT;
    private javax.swing.JButton PASIEN;
    private javax.swing.JButton RESEP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
