/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.apotek;

import entitas.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER TRAVELMATE
 */
public class ObatPasienGUI extends javax.swing.JFrame {
    private Database db;

    /**
     * Creates new form ObatPasienGUI
     */
    private String convertColumnName(String selectedColumn) {
        switch (selectedColumn) {
            case "ID Obat":
                return "id_obat";
            case "Nama Obat":
                return "nama_obat";
            default:
                return ""; // Nilai default jika tidak ada yang cocok
        }
    }
    private void populateTable() {
       DefaultTableModel model = (DefaultTableModel) tblApoteker.getModel();
       model.setRowCount(0); // Mengosongkan tabel
       model.setColumnIdentifiers(new Object[]{"ID Obat", "Nama", "Stok", "Tanggal Kadaluarsa", "Jenis Obat", "Bentuk", "Takaran/Isi"});

       try {
           Database db = new Database();
           db.openConnection();
           db.statement = db.connection.createStatement();

           String query = "SELECT obat.ID_Obat, obat.Nama_Obat, obat.Stok, obat.Tanggal_Kadaluarsa, padat.Bentuk, cair.Ml " +
                          "FROM obat " +
                          "LEFT JOIN padat ON obat.ID_Obat = padat.ID_Obat " +
                          "LEFT JOIN cair ON obat.ID_Obat = cair.ID_Obat";

           ResultSet resultSet = db.statement.executeQuery(query);

           while (resultSet.next()) {
               int id = resultSet.getInt("ID_Obat");
               String nama = resultSet.getString("Nama_Obat");
               String stok = resultSet.getString("Stok");
               String tglKadaluarsa = resultSet.getString("Tanggal_Kadaluarsa");
               String jenisObat = "";
               String bentukObat = "-";
               String takaranIsi = "-";

               if (resultSet.getString("Bentuk") != null) {
                   jenisObat = "Padat";
                   bentukObat = resultSet.getString("Bentuk");
               } else if (resultSet.getString("Ml") != null) {
                   jenisObat = "Cair";
                   takaranIsi = resultSet.getString("Ml") + " mL";
               }

               model.addRow(new Object[]{id, nama, stok, tglKadaluarsa, jenisObat, bentukObat, takaranIsi});
           }

           resultSet.close();
       } catch (SQLException ex) {
           ex.printStackTrace();
           // Handle exceptions
       }
       
   }

    public ObatPasienGUI() {
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblApoteker = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        NamaKolom = new javax.swing.JComboBox<>();
        SearchValue = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblApoteker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblApoteker.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblApoteker);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 600, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Data Obat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 190, 70));

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        NamaKolom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Obat", "Nama Obat" }));
        NamaKolom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaKolomActionPerformed(evt);
            }
        });
        getContentPane().add(NamaKolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        SearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchValueActionPerformed(evt);
            }
        });
        getContentPane().add(SearchValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 170, -1));

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cari : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/curd.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Menutup jendela login
        MenuPasienGUI mainMenu = new MenuPasienGUI();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    private void NamaKolomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaKolomActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NamaKolomActionPerformed

    private void SearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchValueActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String selectedColumn = NamaKolom.getSelectedItem().toString(); // Mendapatkan nama kolom yang dipilih
        String columnName = convertColumnName(selectedColumn); // Mengkonversi ke nama kolom yang sesuai
        String searchValue = SearchValue.getText(); // Mendapatkan nilai yang ingin dicari

        DefaultTableModel model = (DefaultTableModel) tblApoteker.getModel();
        model.setRowCount(0); // Mengosongkan tabel
        model.setColumnIdentifiers(new Object[]{"ID Obat", "Nama", "Stok", "Tanggal Kadaluarsa", "Jenis Obat", "Bentuk", "Takaran/Isi"});

        try {
            Database db = new Database();
            db.openConnection();
            db.statement = db.connection.createStatement();

            String query = "SELECT obat.ID_Obat, obat.Nama_Obat, obat.Stok, obat.Tanggal_Kadaluarsa, padat.Bentuk, cair.Ml " +
               "FROM obat " +
               "LEFT JOIN padat ON obat.ID_Obat = padat.ID_Obat " +
               "LEFT JOIN cair ON obat.ID_Obat = cair.ID_Obat";

            // ...

            // Jika SearchValue tidak kosong, tambahkan kondisi pencarian ke query
            if (!searchValue.isEmpty()) {
                query += " WHERE obat." + columnName + " = '" + searchValue + "'";
            }

            ResultSet resultSet = db.statement.executeQuery(query);

            while (resultSet.next()) {
                int id = resultSet.getInt("ID_Obat");
                String nama = resultSet.getString("Nama_Obat");
                String stok = resultSet.getString("Stok");
                String tglKadaluarsa = resultSet.getString("Tanggal_Kadaluarsa");
                String jenisObat = "";
                String bentukObat = "-";
                String takaranIsi = "-";

                if (resultSet.getString("Bentuk") != null) {
                    jenisObat = "Padat";
                    bentukObat = resultSet.getString("Bentuk");
                } else if (resultSet.getString("Ml") != null) {
                    jenisObat = "Cair";
                    takaranIsi = resultSet.getString("Ml") + " mL";
                }

                model.addRow(new Object[]{id, nama, stok, tglKadaluarsa, jenisObat, bentukObat, takaranIsi});
            }

            resultSet.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle exceptions
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObatPasienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObatPasienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObatPasienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObatPasienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObatPasienGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JComboBox<String> NamaKolom;
    private javax.swing.JTextField SearchValue;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblApoteker;
    // End of variables declaration//GEN-END:variables
}
