/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.apotek;

import entitas.Database;
import entitas.Resep;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER TRAVELMATE
 */
public class ResepGUI extends javax.swing.JFrame {
    private Database db;
    /**
     * Creates new form Resep
     */
    private void populateTable() {
       DefaultTableModel model = (DefaultTableModel) tblApoteker.getModel();
       model.setRowCount(0); // Mengosongkan tabel
       model.setColumnIdentifiers(new Object[]{"ID Resep", "Tanggal Resep", "ID Pasien", "ID Apoteker"});

       try {
            Database db = new Database();
            db.openConnection();
            db.statement = db.connection.createStatement();

            String query = "SELECT * FROM resep";
            ResultSet resultSet = db.statement.executeQuery(query);

            while (resultSet.next()) {
                int id = resultSet.getInt("id_resep");
                String tgl = resultSet.getString("tanggal_resep");
                String pasien = resultSet.getString("pasien_id_pasien");
                String apoteker = resultSet.getString("apoteker_id_apoteker");

                model.addRow(new Object[]{id, tgl, pasien, apoteker});
            }

            resultSet.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle exceptions
        }    
    }
    
    public class DateValidator {
        public static boolean isValidDateFormat(String date, String format) {
            SimpleDateFormat sdf = new SimpleDateFormat(format);
            sdf.setLenient(false); // Non-lenient parsing

            try {
                Date parsedDate = sdf.parse(date);
                return date.equals(sdf.format(parsedDate)); // Ensure the date is exactly the same as input
            } catch (ParseException e) {
                return false;
            }
        }
    }
    
    private boolean isIdDuplicate(String id) {
        try {
            Database db = new Database();
            db.openConnection();
            db.statement = db.connection.createStatement();

            String query = "SELECT * FROM resep WHERE id_resep = " + id;
            ResultSet resultSet = db.statement.executeQuery(query);

            return resultSet.next(); // Mengembalikan true jika ID sudah ada, false jika belum ada

        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle exceptions
        }
        return false;
    }
    
    private boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private void clearFields() {
        txtID.setText("");
        txtIDPAS.setText("");
        txtIDAPT.setText("");
        txtTGL.setText("");
    }
    
    public ResepGUI() {
        initComponents();
        populateTable();
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblApoteker = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIDPAS = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtTGL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        txtIDAPT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblApoteker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblApoteker);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 600, 110));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 60, -1));

        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel4.setText("ID Pasien");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 20));
        getContentPane().add(txtIDPAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 150, -1));
        getContentPane().add(txtTGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 160, -1));

        jLabel6.setText("Tgl. Resep");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 110, 20));

        jLabel3.setText("ID Resep");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Data Resep");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 190, 90));

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));
        getContentPane().add(txtIDAPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, -1));

        jLabel5.setText("ID Apoteker");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/curd.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuApotekerGUI mainMenu = new MenuApotekerGUI();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String id_resep = txtID.getText();
        
        String pasien_id_pasien = txtIDPAS.getText();
        String apoteker_id_apoteker = txtIDAPT.getText();
        String tanggal_resep = txtTGL.getText();
        
        if (isIdDuplicate(id_resep)) {
            JOptionPane.showMessageDialog(this, "ID sudah ada dalam database.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (id_resep.isEmpty() || pasien_id_pasien.isEmpty() || apoteker_id_apoteker.isEmpty() || tanggal_resep.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!ObatGUI.DateValidator.isValidDateFormat(tanggal_resep, "dd-MM-yy")) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid. Gunakan format dd-MM-yy", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!isInteger(id_resep)) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int id = Integer.parseInt(id_resep);
            // Buat objek Resep dan isi dengan data yang diambil dari GUI
            Resep resep = new Resep();
            resep.id_resep = id;
            resep.pasien_id_pasien = pasien_id_pasien;
            resep.apoteker_id_apoteker = apoteker_id_apoteker;
            resep.tanggal_resep = tanggal_resep;
            
            // Tambahkan data ke database
            if (resep.create()) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // Bersihkan input setelah berhasil menambahkan data
                clearFields();
                // Perbarui tabel setelah menambahkan data baru
                populateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan data.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String id_resep = txtID.getText();
        String pasien_id_pasien = txtIDPAS.getText();
        String apoteker_id_apoteker = txtIDAPT.getText();
        String tanggal_resep = txtTGL.getText();
        
        if (id_resep.isEmpty() || pasien_id_pasien.isEmpty() || apoteker_id_apoteker.isEmpty() || tanggal_resep.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!ObatGUI.DateValidator.isValidDateFormat(tanggal_resep, "dd-MM-yy")) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid. Gunakan format dd-MM-yy", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!isInteger(id_resep)) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int id = Integer.parseInt(id_resep);
            // Buat objek Resep dan isi dengan data yang diambil dari GUI
            Resep resep = new Resep();
            resep.id_resep = id;
            resep.pasien_id_pasien = pasien_id_pasien;
            resep.apoteker_id_apoteker = apoteker_id_apoteker;
            resep.tanggal_resep = tanggal_resep;
            
            // Tambahkan data ke database
            if (resep.update()) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // Bersihkan input setelah berhasil menambahkan data
                clearFields();
                // Perbarui tabel setelah menambahkan data baru
                populateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengupdate data.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String id_resep = txtID.getText();

        // Validasi input, pastikan ID yang akan dihapus tidak kosong
        if (id_resep.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Obat harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!isInteger(id_resep)) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(id_resep);

            Resep resep = new Resep();

            // Hapus data berdasarkan ID
           if (resep.delete(id)) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // Bersihkan input setelah berhasil menghapus data
                clearFields();
                // Perbarui tabel setelah menghapus data
                populateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblApoteker;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDAPT;
    private javax.swing.JTextField txtIDPAS;
    private javax.swing.JTextField txtTGL;
    // End of variables declaration//GEN-END:variables
}
