/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.apotek;

import entitas.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER TRAVELMATE
 */
public class ResepPasienGUI extends javax.swing.JFrame {
    private Database db;
    /**
     * Creates new form ResepGUI2
     */
    private String convertColumnName(String selectedColumn) {
        switch (selectedColumn) {
            case "ID Resep":
                return "id_resep";
            case "ID Pasien":
                return "pasien_id_pasien";
            default:
                return ""; // Nilai default jika tidak ada yang cocok
        }
    }
    
    private void populateTable() {
       DefaultTableModel model = (DefaultTableModel) tblApoteker.getModel();
       model.setRowCount(0); // Mengosongkan tabel
       model.setColumnIdentifiers(new Object[]{"ID Resep", "Tanggal Resep", "ID Pasien", "ID Apoteker"});

       try {
            Database db = new Database();
            db.openConnection();
            db.statement = db.connection.createStatement();

            String query = "SELECT * FROM resep";
            ResultSet resultSet = db.statement.executeQuery(query);

            while (resultSet.next()) {
                int id = resultSet.getInt("id_resep");
                String tgl = resultSet.getString("tanggal_resep");
                String pasien = resultSet.getString("pasien_id_pasien");
                String apoteker = resultSet.getString("apoteker_id_apoteker");

                model.addRow(new Object[]{id, tgl, pasien, apoteker});
            }

            resultSet.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle exceptions
        }    
   }
    
    public ResepPasienGUI() {
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblApoteker = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SearchValue = new javax.swing.JTextField();
        NamaKolom = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblApoteker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblApoteker);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 600, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Data Resep");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 190, 90));

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cari : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        SearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchValueActionPerformed(evt);
            }
        });
        getContentPane().add(SearchValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 170, -1));

        NamaKolom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Resep", "ID Pasien" }));
        NamaKolom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaKolomActionPerformed(evt);
            }
        });
        getContentPane().add(NamaKolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/curd.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Menutup jendela login
        MenuPasienGUI mainMenu = new MenuPasienGUI();
        mainMenu.setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    private void SearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchValueActionPerformed

    private void NamaKolomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaKolomActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NamaKolomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedColumn = NamaKolom.getSelectedItem().toString(); // Mendapatkan nama kolom yang dipilih
        String columnName = convertColumnName(selectedColumn); // Mengkonversi ke nama kolom yang sesuai
        String searchValue = SearchValue.getText(); // Mendapatkan nilai yang ingin dicari

        DefaultTableModel model = (DefaultTableModel) tblApoteker.getModel();
        model.setRowCount(0); // Mengosongkan tabel
        model.setColumnIdentifiers(new Object[]{"ID Resep", "Tanggal Resep", "ID Pasien", "ID Apoteker"});

        try {
            Database db = new Database();
            db.openConnection();
            db.statement = db.connection.createStatement();

            String query = "SELECT * FROM resep";

            // Jika SearchValue tidak kosong, tambahkan kondisi pencarian ke query
            if (!searchValue.isEmpty()) {
                query += " WHERE " + columnName + " = '" + searchValue + "'";
            } else {
                // Jika SearchValue kosong, jalankan populateTable() untuk menampilkan semua data
                populateTable();
                return;
            }

            ResultSet resultSet = db.statement.executeQuery(query);

            while (resultSet.next()) {
                int id = resultSet.getInt("id_resep");
                String tgl = resultSet.getString("tanggal_resep");
                String pasien = resultSet.getString("pasien_id_pasien");
                String apoteker = resultSet.getString("apoteker_id_apoteker");

                model.addRow(new Object[]{id, tgl, pasien, apoteker});
            }

            resultSet.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle exceptions
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepPasienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepPasienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepPasienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepPasienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepPasienGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembali;
    private javax.swing.JComboBox<String> NamaKolom;
    private javax.swing.JTextField SearchValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblApoteker;
    // End of variables declaration//GEN-END:variables
}
